### ISSUE TITLE
adding timestamps to offers on `Marketplace` 

### ISSUE THREAD

**Issue by skoshx** [thirdweb-dev/contracts#176]
It would be nice to see when offers are made on marketplace auction listings. This increases transparency. I am willing to submit a Pull Request to add this new feature.

The changed `Offer` structure would look _something_ like this:

```solidity
struct Offer {
        uint256 listingId;
        address offeror;
        uint256 quantityWanted;
        address currency;
        uint256 pricePerToken;
        uint256 expirationTimestamp;
        uint256 createdAtTimestamp;
}
```

**Comment by nkrishang** [comment]
Hi @skoshx 👋🏽 

The time at which an offer is created can be queried by listening to event logs on the Marketplace. (Particularly, the `NewOffer` event emitted whenever an offer is made.)

Since the information about when an offer is created is not relevant for any job that the Marketplace contract performs, the information is not stored in the contract's state.

To note -- we are working on the next iteration of the Marketplace smart contract which you can track, here: https://github.com/thirdweb-dev/contracts/pull/259
