### ISSUE TITLE
initializer was called without prompting deployer for values. 

### ISSUE THREAD

**Issue by adamwong246** [thirdweb-dev/contracts#256]
Firstly, this might not be the best place to post this but I'm locked out of discord right now because phone number was attached to a lost account. Please bear with me while I get that under control. 

Secondly, the source: https://gist.github.com/adamwong246/628169607ad638b5c5e05ce3cba5fdbc

I have created a contract which extends `DropERC721`. Upon deploying, I notice some things
1) The UI does not prompt me for the recipient address, name of collection, etc
2) Once deployed, the event log shows  the initialization, though the event data is empty. I had expected to see several RoleGranted events based on the input from the previous step.
3) Attempting to manually initialize the contract fails predictably, as it's already been initialized. 

All of this leads me to suspect that the thirdweb deployer is not picking up the correct initialization params and is passing empty values rather than allowing the user to enter those details through the deployment wizard. Of course, I could be wildly off course. Either way, could I get an explanation for why my contract seems to have initialized with empty values?

**Comment by nkrishang** [comment]
Hey @adamwong246 👋🏽 

If you deploy your contract `indigidaoDropERC721` via `thirdweb deploy`, the UI will not prompt you to fill in the arguments that `DropERC721`'s `initialize` function accepts. That is because the UI will prompt you only to fill in the arguments accepted by the constructor of the contract (which, in this case, accepts no arguments).

The UI will prompt you to fill in arguments for the `initialize` function when you're deploying a proxy smart contract that points to a deployed `indigidaoDropERC721` contract. To accomplish this flow:

- Release your smart contract. Run the following:
```bash
npx thirdweb@latest release
```
- When filling in details for your contract's release, select the "**Deployable via proxy**" option. This informs thirdweb's infra that your contract is meant to be consumed via a proxy contract pointing to it. The UI will let you deploy the implementation of your `indigidaoDropERC721` contract to the various supported networks.

- After completing the above, whenever you try to deploy your contract via its release page, the UI will have you deploy a proxy pointing to the appropriate implementation of your contract, and let you fill in arguments accepted by the `initialize` function.

Hope this helps!
