### ISSUE TITLE
Inaccurate comment about MINTER_ROLE in code

### ISSUE THREAD

**Issue by elie222** [thirdweb-dev/contracts#301]
This comment in the code is inaccurate:

> @notice Verifies that a mint request is signed by an account holding MINTER_ROLE (at the time of the function call).

https://github.com/thirdweb-dev/contracts/blob/main/contracts/extension/interface/ISignatureMintERC721.sol#L50-L51

It isn't dependent on MINTER_ROLE; in the thirdweb implementation, it actually checks for `owner()`:

```js
    function _canSignMintRequest(address _signer) internal view virtual override returns (bool) {
        return _signer == owner();
    }
```

https://github.com/thirdweb-dev/contracts/blob/main/contracts/base/ERC721SignatureMint.sol#L86-L88

**Comment by kumaryash90** [comment]
@elie222 This is a common interface used by different contracts in our repository. The function is supposed to check for MINTER_ROLE (or equivalent).
For the contracts in contract-kit, the equivalent is assigned to `owner` for all roles since we don't implement explicit role-based access control there.

Thanks for pointing it out though. We will update the comments with more generic description.
Closing this for now.
