### ISSUE TITLE
Issue with `maxClaimable` when overriding claim condition for wallets

### ISSUE THREAD

**Issue by resurrexi** [thirdweb-dev/contracts#361]
Hi, I was going through the docs on overriding the default claim condition of the NFT Drop contract. After reading your [blog post](https://blog.thirdweb.com/announcing-improved-claim-conditions/) and the [docs](https://portal.thirdweb.com/react/react.usesetclaimconditions#snapshot), it appears that the `maxClaimable` is set in "wei" units, meaning if I define `maxClaimable` on an address to be `5`, and then I later call `useActiveClaimConditionForWallet` in my React app, the [`maxClaimablePerWallet`](https://portal.thirdweb.com/react/react.useactiveclaimconditionforwallet#return-value) of the React hook is `0.000000000000000005`.

I don't think this is the intent here. Anyways, it seemed like the only way to circumvent this issue is to just multiply my custom value by 10^18.

**Comment by boakhnh** [comment]
yes

**Comment by nkrishang** [comment]
Hey @resurrexi 👋🏽  apologies on getting to this so late. Where are you with this issue / were you able to resolve it?

At the smart contract level, `maxClaimablePerWallet` / `quantityLimitPerWallet` is not in wei units since the quantity in question is for NFTs, whose quantity is always considered in whole units.

I highly suggest tagging `@thirdweb Support` with this issue in the [thirdweb discord](https://discord.gg/beY2nwTP), where we can better facilitate debugging this issue.

Thanks!
