### ISSUE TITLE
Fix token deploy contract

### ISSUE THREAD

**Issue by VXEAD** [thirdweb-dev/contracts#548]
After i make deploy i cant add  it on dashboard, and no trans approve in metamask. So its freeze and i cant make any opt with contract. Just -0.4$  

https://imgur.com/a/q9Jhmj9

**Comment by nkrishang** [comment]
Hi @VXEAD :wave: sorry you're facing this issue!

Looks like the 'add to dashboard' transaction may have been broken / interrupted at the time. You can add your contract to your dashboard from it's contract page `thirdweb.com/{network}/{contract-address}` where you will see an 'Add to Dashboard' button.

If you want to search for your contract's address, you can do so by checking your wallet's transaction history page on the respective network's block explorer (e.g. Etherscan for Ethereum mainnet).

Closing this issue here. Please feel free to tag `@thirdweb Support` with this issue in the [thirdweb discord](https://discord.gg/beY2nwTP).
